### ISSUE TITLE
Svelte Starter Broken (setup is not a function)

### ISSUE THREAD

**Issue by p1u3o** [adonisjs/inertia-starter-kit#7]
### Package version

2.1.0

### Describe the bug

Initialising the default intertia starter kit with svelte ends up with a crash when a route is requested

```
11:53:47 [vite-plugin-svelte] inertia/pages/home.svelte:10:4 Buttons and links should either contain text or have an `aria-label` or `aria-labelledby` attribute
https://svelte.dev/e/a11y_consider_explicit_label
[11:53:47.259] ERROR (34970): setup is not a function
    request_id: "ge8dkkacuhe62z1u012yk0tu"
    x-request-id: "ge8dkkacuhe62z1u012yk0tu"
    err: {
      "type": "TypeError",
      "message": "setup is not a function",
      "stack":
          TypeError: setup is not a function
              at createInertiaApp (/Users/pluto/Documents/Projects/neutron/node_modules/@inertiajs/svelte/dist/createInertiaApp.js:14:23)
              at async _ServerRenderer.render (file:///Users/pluto/Documents/Projects/neutron/node_modules/@adonisjs/inertia/build/chunk-DLEGZFQ5.js:25:20)
              at async #renderOnServer (file:///Users/pluto/Documents/Projects/neutron/node_modules/@adonisjs/inertia/build/chunk-DLEGZFQ5.js:249:28)
              at async ShieldMiddleware.handle (/Users/pluto/Documents/Projects/neutron/node_modules/@adonisjs/shield/src/shield_middleware.ts:64:5)
              at async SessionMiddleware.handle (/Users/pluto/Documents/Projects/neutron/node_modules/@adonisjs/session/src/session_middleware.ts:81:22)
              at async InertiaMiddleware.handle (file:///Users/pluto/Documents/Projects/neutron/node_modules/@adonisjs/inertia/build/chunk-DLEGZFQ5.js:364:5)
              at async ViteMiddleware.handle (/Users/pluto/Documents/Projects/neutron/node_modules/@adonisjs/vite/src/vite_middleware.ts:42:5)
              at async <anonymous> (/Users/pluto/Documents/Projects/neutron/node_modules/@adonisjs/static/src/static_middleware.ts:74:11)
      "status": 500
    }
```

<img width="1710" alt="image" src="https://github.com/user-attachments/assets/f5749b14-612e-4b40-ac99-fda8aefe1c06" />

Reproduction (project at https://github.com/p1u3o/intertia-template-failure)

```
$ node --version
v23.5.0
$ npm init adonisjs@latest -- -K=inertia --adapter=svelte --ssr

> npx
> create-adonisjs -K=inertia --adapter=svelte --ssr


     _       _             _         _ ____
    / \   __| | ___  _ __ (_)___    | / ___|
   / _ \ / _` |/ _ \| '_ \| / __|_  | \___ \
  / ___ \ (_| | (_) | | | | \__ \ |_| |___) |
 /_/   \_\__,_|\___/|_| |_|_|___/\___/|____/


❯ Where should we create your new project · ./neutron
❯ Which authentication guard you want to use · skip
❯ Which database driver you want to use · libsql
❯ Download starter kit (477 ms)
  Downloaded "github:adonisjs/inertia-starter-kit"
❯ Install packages (32 s)
  Packages installed using "npm"
❯ Prepare application (266 ms)
  Application ready
❯ Configure Lucid (6.04 s)
  Lucid configured to use "libsql" database
❯ Configure Inertia (5.82 s)
  Inertia configured
╭──────────────────────────────────────────────────────────────────╮
│    Your AdonisJS project has been created successfully!          │
│──────────────────────────────────────────────────────────────────│
│                                                                  │
│    ❯ cd neutron                                                  │
│    ❯ npm run dev                                                 │
│    ❯ Open http://localhost:3333                                  │
│    ❯                                                             │
│    ❯ Have any questions?                                         │
│    ❯ Join our Discord server - https://discord.gg/vDcEjq6        │
│                                                                  │
╰──────────────────────────────────────────────────────────────────╯

$ cd neutron
$ npm run dev
```

### Reproduction repo

https://github.com/p1u3o/intertia-template-failure

**Comment by p1u3o** [comment]
Starting a project without SSR throws a different error in the browser

```
Uncaught (in promise) Svelte error: component_api_invalid_new
Attempted to instantiate node_modules/@inertiajs/svelte/dist/components/App.svelte with `new App`, which is no longer valid in Svelte 5. If this component is not under your control, set the `compatibility.componentApi` compiler option to `4` to keep it working.
https://svelte.dev/e/component_api_invalid_new
    at component_api_invalid_new (http://localhost:3333/node_modules/.vite/deps/chunk-6B2HMSQ2.js?v=6b1bd2eb:127:19)
    at check_target (http://localhost:3333/node_modules/.vite/deps/chunk-FGIPJSKK.js?v=6b1bd2eb:310:5)
    at new App (http://localhost:3333/node_modules/.vite/deps/@inertiajs_svelte.js?v=4353bae4:8753:3)
    at http://localhost:3333/node_modules/.vite/deps/chunk-FGIPJSKK.js?v=6b1bd2eb:283:26
    at update_reaction (http://localhost:3333/node_modules/.vite/deps/chunk-6B2HMSQ2.js?v=6b1bd2eb:1308:23)
    at update_effect (http://localhost:3333/node_modules/.vite/deps/chunk-6B2HMSQ2.js?v=6b1bd2eb:1399:21)
    at create_effect (http://localhost:3333/node_modules/.vite/deps/chunk-6B2HMSQ2.js?v=6b1bd2eb:2474:7)
    at branch (http://localhost:3333/node_modules/.vite/deps/chunk-6B2HMSQ2.js?v=6b1bd2eb:2622:10)
    at http://localhost:3333/node_modules/.vite/deps/chunk-FGIPJSKK.js?v=6b1bd2eb:277:17
    at update_reaction (http://localhost:3333/node_modules/.vite/deps/chunk-6B2HMSQ2.js?v=6b1bd2eb:1308:23)
```

which seems to be due to Svelte 4 => 5 differences

**Comment by p1u3o** [comment]
I think I've managed to solve the problem.

The ssr version of the Inertia adapter does not pass a setup function to createInertiaApp. Passing render from svelte/server solves the problem. Happy to make a MR if this is the correct approach.

https://github.com/adonisjs/inertia/blob/main/stubs/svelte/ssr.ts.stub

```

import { createInertiaApp } from '@inertiajs/svelte'
import { render as svelteRender } from 'svelte/server'

export default function render(page: any) {
  return createInertiaApp({
    page,
    resolve: (name) => {
      const pages = import.meta.glob('../pages/**/*.svelte', { eager: true })
      return pages[`../pages/${name}.svelte`]
    },
    setup({ el, App, props }) {
      return svelteRender(App, { props })  
    },
  })
}
```

**Comment by RomainLanz** [comment]
Hey @p1u3o! 👋🏻 

Yes, that's likely the issue. I'm not a Svelte user myself, but it makes sense that Svelte would also require a `setup` function.

Happy to accept a PR!

**Comment by p1u3o** [comment]
The last hurdle I can't seem to solve is that file resolution on relative imports is not working as expected, this breaks using libraries such as shadcn-svelte.

This does not work

```
import MyComponent from './parts/component.svelte'
```

But using exact path does (well using the alias)

```
import MyComponent from '~/parts/component.svelte'
```

This is with SSR both on and off.

Otherwise, everything else is working with Svelte 5 and Inertia with Adonis.
